//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECOLABOR.Apresentacao.Menu {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class frmCadastroNovaPlanilha {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal frmCadastroNovaPlanilha() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECOLABOR.Apresentacao.Menu.frmCadastroNovaPlanilha", typeof(frmCadastroNovaPlanilha).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=478,Y=24}.
        /// </summary>
        public static System.Drawing.Point btnAbrirArquivo_Location {
            get {
                object obj = ResourceManager.GetObject("btnAbrirArquivo.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=24, Height=21}.
        /// </summary>
        public static System.Drawing.Size btnAbrirArquivo_Size {
            get {
                object obj = ResourceManager.GetObject("btnAbrirArquivo.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int btnAbrirArquivo_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnAbrirArquivo.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string btnAbrirArquivo_Text {
            get {
                return ResourceManager.GetString("btnAbrirArquivo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Bottom, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles btnProximo_Anchor {
            get {
                object obj = ResourceManager.GetObject("btnProximo.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to On.
        /// </summary>
        public static System.Windows.Forms.ImeMode btnProximo_ImeMode {
            get {
                object obj = ResourceManager.GetObject("btnProximo.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=773,Y=389}.
        /// </summary>
        public static System.Drawing.Point btnProximo_Location {
            get {
                object obj = ResourceManager.GetObject("btnProximo.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
        /// </summary>
        public static System.Drawing.Size btnProximo_Size {
            get {
                object obj = ResourceManager.GetObject("btnProximo.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 7.
        /// </summary>
        public static int btnProximo_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnProximo.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próximo.
        /// </summary>
        public static string btnProximo_Text {
            get {
                return ResourceManager.GetString("btnProximo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Bottom, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles dtViewConfig_Anchor {
            get {
                object obj = ResourceManager.GetObject("dtViewConfig.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=637,Y=146}.
        /// </summary>
        public static System.Drawing.Point dtViewConfig_Location {
            get {
                object obj = ResourceManager.GetObject("dtViewConfig.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=217, Height=237}.
        /// </summary>
        public static System.Drawing.Size dtViewConfig_Size {
            get {
                object obj = ResourceManager.GetObject("dtViewConfig.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        public static int dtViewConfig_TabIndex {
            get {
                object obj = ResourceManager.GetObject("dtViewConfig.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles groupBox1_Anchor {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=637,Y=12}.
        /// </summary>
        public static System.Drawing.Point groupBox1_Location {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=217, Height=128}.
        /// </summary>
        public static System.Drawing.Size groupBox1_Size {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 7.
        /// </summary>
        public static int groupBox1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("groupBox1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planilhas no Arquivo.
        /// </summary>
        public static string groupBox1_Text {
            get {
                return ResourceManager.GetString("groupBox1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=15,Y=12}.
        /// </summary>
        public static System.Drawing.Point groupBox2_Location {
            get {
                object obj = ResourceManager.GetObject("groupBox2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=508, Height=52}.
        /// </summary>
        public static System.Drawing.Size groupBox2_Size {
            get {
                object obj = ResourceManager.GetObject("groupBox2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        public static int groupBox2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("groupBox2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o Arquivo.
        /// </summary>
        public static string groupBox2_Text {
            get {
                return ResourceManager.GetString("groupBox2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=304,Y=82}.
        /// </summary>
        public static System.Drawing.Point groupBox3_Location {
            get {
                object obj = ResourceManager.GetObject("groupBox3.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=219, Height=52}.
        /// </summary>
        public static System.Drawing.Size groupBox3_Size {
            get {
                object obj = ResourceManager.GetObject("groupBox3.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 7.
        /// </summary>
        public static int groupBox3_TabIndex {
            get {
                object obj = ResourceManager.GetObject("groupBox3.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe I.T..
        /// </summary>
        public static string groupBox3_Text {
            get {
                return ResourceManager.GetString("groupBox3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=15,Y=82}.
        /// </summary>
        public static System.Drawing.Point groupBox4_Location {
            get {
                object obj = ResourceManager.GetObject("groupBox4.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=283, Height=52}.
        /// </summary>
        public static System.Drawing.Size groupBox4_Size {
            get {
                object obj = ResourceManager.GetObject("groupBox4.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 8.
        /// </summary>
        public static int groupBox4_TabIndex {
            get {
                object obj = ResourceManager.GetObject("groupBox4.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe Modelo.
        /// </summary>
        public static string groupBox4_Text {
            get {
                return ResourceManager.GetString("groupBox4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Bottom, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles treeView1_Anchor {
            get {
                object obj = ResourceManager.GetObject("treeView1.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=19}.
        /// </summary>
        public static System.Drawing.Point treeView1_Location {
            get {
                object obj = ResourceManager.GetObject("treeView1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=205, Height=103}.
        /// </summary>
        public static System.Drawing.Size treeView1_Size {
            get {
                object obj = ResourceManager.GetObject("treeView1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        public static int treeView1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("treeView1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=25}.
        /// </summary>
        public static System.Drawing.Point txtCaminhoArquivo_Location {
            get {
                object obj = ResourceManager.GetObject("txtCaminhoArquivo.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=477, Height=20}.
        /// </summary>
        public static System.Drawing.Size txtCaminhoArquivo_Size {
            get {
                object obj = ResourceManager.GetObject("txtCaminhoArquivo.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int txtCaminhoArquivo_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtCaminhoArquivo.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=25}.
        /// </summary>
        public static System.Drawing.Point txtIT_Location {
            get {
                object obj = ResourceManager.GetObject("txtIT.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=207, Height=20}.
        /// </summary>
        public static System.Drawing.Size txtIT_Size {
            get {
                object obj = ResourceManager.GetObject("txtIT.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        public static int txtIT_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtIT.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=6,Y=25}.
        /// </summary>
        public static System.Drawing.Point txtModelo_Location {
            get {
                object obj = ResourceManager.GetObject("txtModelo.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=271, Height=20}.
        /// </summary>
        public static System.Drawing.Size txtModelo_Size {
            get {
                object obj = ResourceManager.GetObject("txtModelo.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int txtModelo_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtModelo.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Bottom, Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles webBrowser1_Anchor {
            get {
                object obj = ResourceManager.GetObject("webBrowser1.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=15,Y=146}.
        /// </summary>
        public static System.Drawing.Point webBrowser1_Location {
            get {
                object obj = ResourceManager.GetObject("webBrowser1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=20, Height=20}.
        /// </summary>
        public static System.Drawing.Size webBrowser1_MinimumSize {
            get {
                object obj = ResourceManager.GetObject("webBrowser1.MinimumSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=616, Height=266}.
        /// </summary>
        public static System.Drawing.Size webBrowser1_Size {
            get {
                object obj = ResourceManager.GetObject("webBrowser1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        public static int webBrowser1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("webBrowser1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
